version: '3.8'

services:

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd dhioru-app && npm start"
    ports:
      - "8000:3000"
    stdin_open: true

  #本番ではDBはRDSをつかうのでこちらはオフ！
  db:
    image: mysql:5.7
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

  api: #rubyね
    build:
      context: ./api/
# =========ローカルと本番切り替え===========
    #command: bundle exec puma -C config/puma.rb -e production
    command: bundle exec puma -C config/puma.rb
# ======================================
    volumes:
      - ./api:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    networks:
      - app-network
    ports:               #変更(追加)
      - 3000:3000
    #本番環境ではオフ！
    depends_on:
      - db

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  app-network:
    external: true
